sudo: required
language: generic

branches:
    # Avoid building PR branches.
    only:
        - master
        - ci
        - releases
        - /^v\d+(\.\d+)*$/

matrix:
    fast_finish:
        true

    include:
        - os: linux
          dist: trusty
          sudo: false
          language: python
          python: "2.7"
          addons:
              apt: {packages: [python-mock]}

        - os: linux
          dist: trusty
          sudo: false
          language: python
          python: "3.5"

        - os: linux
          dist: trusty
          sudo: false
          language: python
          python: "3.6"

        - os: linux
          dist: trusty
          sudo: false
          language: python
          python: "3.7-dev"

    allow_failures:
        - python: "3.7-dev"

cache:
    pip

script:
    - sudo python setup.py test
